name: DeployToDev

# feature 브랜치에서 DEV 환경에 배포 필요 시 수동으로 Workflow를 수행한다.
# 대상 feature 브랜치의 최신 commit으로 배포

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
    inputs:
      # Checkout 시 필요한 데이터
      repository:
        type: string
        required: true
      ref_name:
        type: string
        required: true
      # AWS 배포 시 필요한 데이터
      commit:
        type: string
        required: true
      environment:
        type: string
        required: true
      region:
        type: string
        required: true
      account_id_dev:
        type: string
        required: true
      account_id_stg:
        type: string
        required: true
      account_id_prod:
        type: string
        required: true
      product_code:
        type: string
        required: true
      application_code:
        type: string
        required: true
      s3_api_doc_folder_name:
        type: string
        required: false
      # Slack 송신에 필요한 데이터
      server_name:
        type: string
        required: false

jobs:
  CheckBranch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if '${{ startsWith(inputs.ref_name, 'feature/') || startsWith(inputs.ref_name, 'develop') }}';
          then
            echo "Valid branch ${{ inputs.ref_name }}"
          else
            echo "Invalid branch ${{ inputs.ref_name }}"
            exit 1
          fi

  GetAwsValue:
    needs: [CheckBranch]
    uses: ./.github/workflows/GetAwsValue.yml
    with:
      environment: ${{ inputs.environment }}
      region: ${{ inputs.region }}
      account_id_dev: ${{ inputs.account_id_dev }}
      account_id_stg: ${{ inputs.account_id_stg }}
      account_id_prod: ${{ inputs.account_id_prod }}
      product_code: ${{ inputs.product_code }}
      application_code: ${{ inputs.application_code }}
      s3_api_doc_folder_name: ${{ inputs.s3_api_doc_folder_name }}

  BuildAndDeployToDev:
    if: ${{ startsWith(inputs.ref_name, 'feature/') }}
    uses: ./.github/workflows/Deploy.yml
    needs: [GetAwsValue]
    secrets: inherit
    with:
      repository: ${{ inputs.repository }}
      ref_name: ${{ inputs.ref_name }}
      commit: ${{ inputs.commit }}
      environment: ${{ inputs.environment }}
      region: ${{ inputs.region }}
      ecr_registry: ${{ needs.GetAwsValue.outputs.ecr_registry }}
      ecr_repository: ${{ needs.GetAwsValue.outputs.ecr_repository }}
      task_definition: ${{ needs.GetAwsValue.outputs.task_definition }}
      container: ${{ needs.GetAwsValue.outputs.container }}
      service: ${{ needs.GetAwsValue.outputs.service }}
      cluster: ${{ needs.GetAwsValue.outputs.cluster }}
      api_doc: ${{ needs.GetAwsValue.outputs.api_doc }}
      version: ${{ inputs.ref_name }}
