name: DeployOciToProd

# Main 브랜치에서 가장 최근의 TAG로 AWS 배포 하는 Workflow

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
    inputs:
      # Checkout 시 필요한 데이터
      repository:
        type: string
        required: true
      ref_name:
        type: string
        required: true
      # OCI 배포 시 필요한 데이터
      commit:
        type: string
        required: true
      npm_token:
        type: string
        required: true
      environment:
        type: string
        required: true
      region:
        type: string
        required: true
      server_code:
        type: string
        required: true
      # Slack 송신에 필요한 데이터
      server_name:
        type: string
        required: false
      # LOL Default Platform
      platform:
        type: string
        required: false
      # 캐시 사용 여부
      use_cache:
        type: string
        required: false

jobs:
  CheckBranch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if '${{ inputs.ref_name == 'main' }}';
          then
            echo "Valid branch ${{ inputs.ref_name }}"
          else
            echo "Invalid branch ${{ inputs.ref_name }}"
            exit 1
          fi

  # Main 브랜치에서 가장 최근의 TAG를 가져온다
  GetLatestTag:
    needs: [CheckBranch]
    if: ${{ inputs.ref_name == 'main' }}
    uses: ./.github/workflows/GetLatestTag.yml
    with:
      environment: ${{ inputs.environment }}
      repository: ${{ inputs.repository }}
      ref_name: ${{ inputs.ref_name }}

  # tag이름으로 배포할 commit 확인
  GetCommitFromTag:
    if: ${{ inputs.ref_name == 'main' }}
    uses: ./.github/workflows/GetCommitFromTag.yml
    needs: [GetLatestTag]
    with:
      tag: ${{ needs.GetLatestTag.outputs.tag }}
      repository: ${{ inputs.repository }}
      ref_name: ${{ inputs.ref_name }}

  GetOciValue:
    needs: [CheckBranch]
    uses: ./.github/workflows/GetOciValue.yml
    with:
      region: ${{ inputs.region }}
      environment: ${{ inputs.environment }}
      server_code: ${{ inputs.server_code }}

  BuildAndDeployToProd:
    if: ${{ inputs.ref_name == 'main' }}
    uses: ./.github/workflows/DeployOci.yml
    needs: [GetCommitFromTag, GetOciValue]
    secrets: inherit
    with:
      repository: ${{ inputs.repository }}
      ref_name: ${{ inputs.ref_name }}
      npm_token: ${{ inputs.npm_token }}
      environment: ${{ inputs.environment }}
      oci_region: ${{ inputs.region }}
      server_code: ${{ inputs.server_code }}
      platform: ${{ inputs.platform }}
      version: ${{ inputs.version }}
      commit: ${{ needs.GetCommitFromTag.outputs.commit }}
      oci_registry_username: ${{ needs.GetOciValue.outputs.oci_registry_username }}
      oci_registry_password: ${{ needs.GetOciValue.outputs.oci_registry_password }}
      oci_registry: ${{ needs.GetOciValue.outputs.oci_registry }}
      oci_repository: ${{ needs.GetOciValue.outputs.oci_repository }}
      oci_config: ${{ needs.GetOciValue.outputs.oci_config }}
      oci_passphrase: ${{ needs.GetOciValue.outputs.oci_passphrase }}
      oci_oke_ocid: ${{ needs.GetOciValue.outputs.oci_oke_ocid }}
      oci_region_key: ${{ needs.GetOciValue.outputs.oci_region_key }}
      deployment: ${{ needs.GetOciValue.outputs.deployment }}

  NotifyToSlackToSuccess:
    if: ${{ success() }}
    needs: [GetLatestTag, GetCommitFromTag, BuildAndDeployToProd]
    uses: ./.github/workflows/NotifyToSlack.yml
    secrets: inherit
    with:
      server_name: ${{ inputs.server_name }}
      environment: ${{ inputs.environment }}
      version: ${{ needs.GetLatestTag.outputs.tag }}
      status: success
      region: ${{ inputs.region }}
      commit: ${{ needs.GetCommitFromTag.outputs.commit }}

  NotifyToSlackToFail:
    if: ${{ failure() }}
    needs: [GetLatestTag, GetCommitFromTag, BuildAndDeployToProd]
    uses: ./.github/workflows/NotifyToSlack.yml
    secrets: inherit
    with:
      server_name: ${{ inputs.server_name }}
      environment: ${{ inputs.environment }}
      version: ${{ needs.GetLatestTag.outputs.tag }}
      status: failure
      region: ${{ inputs.region }}
      commit: ${{ needs.GetCommitFromTag.outputs.commit }}
