name: SetTagForProd

# release/hotfix 브랜치에서 main으로 머지 후 PROD 환경 배포 전 Tag를 생성하기 위한 수동 Workflow
# hotfix 브랜치면 1.0.0+hotfix.yymmdd
# release 브랜치면 1.0.0+yymmdd
# main에 Tag 생성 후 main에 생성된 Tag로 서버 배포를 진행한다.

# inputs:
# repository: Checkout 할 저장소
# ref_name: Checkout 할 브랜치 이름
on:
  workflow_call:
    inputs:
      repository:
        type: string
        required: true
      ref_name:
        type: string
        required: true

jobs:
  CheckBranch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if '${{ startsWith(inputs.ref_name, 'release/') || startsWith(inputs.ref_name, 'hotfix/') }}';
          then
            echo "Valid branch ${{ inputs.ref_name }}"
          else
            echo "Invalid branch ${{ inputs.ref_name }}"
            exit 1
          fi

  # release/hotfix 브랜치에서 배포 버전 추출
  # hotfix 브랜치면 1.0.0+hotfix.yymmdd
  # release 브랜치면 1.0.0+yymmdd
  ExtractVersion:
    needs: [CheckBranch]
    if: ${{ startsWith(inputs.ref_name, 'release/') || startsWith(inputs.ref_name, 'hotfix/') }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{ env.VERSION }}
    steps:
      - name: Extract Version Name
        run: |
          if '${{ startsWith(inputs.ref_name, 'hotfix/') }}'
          then
            echo "VERSION=$(echo '${{ inputs.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')+hotfix.$(echo '${{ inputs.ref_name }}' | egrep -o '[0-9]{6}')" >> $GITHUB_ENV
          elif '${{ startsWith(inputs.ref_name, 'release/') }}'
          then
            echo "VERSION=$(echo '${{ inputs.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\+[0-9]{6}')" >> $GITHUB_ENV
          else
            echo ""
          fi

      - name: Print Version
        run: |
          echo VERSION = ${{ env.VERSION }}

  # release/hotfix -> main 브랜치로 merge 후 release/hotfix 브랜치 삭제 -> main 브랜치 태깅
  SetTagForProd:
    if: ${{ needs.ExtractVersion.outputs.version != '' }}
    needs: [ExtractVersion]
    runs-on: ubuntu-latest
    steps:
      - name: Start SetTagForProd Workflow
        run: |
          echo Start SetTagForProd Workflow

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref_name }}

      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

      # release/hotfix -> main 브랜치로 merge -> main 브랜치에 버전 태깅
      - name: Merge to main
        run: |
          git fetch --unshallow
          git checkout main
          git pull
          git merge --no-ff ${{ inputs.ref_name }} -m "Auto-merge from ${{ inputs.ref_name }} to main"
          git push
          git tag ${{ needs.ExtractVersion.outputs.version }}
          git push origin ${{ needs.ExtractVersion.outputs.version }}

      # github release 등록
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.ExtractVersion.outputs.version }}
          release_name: ${{ needs.ExtractVersion.outputs.version }}

      # release/hotfix 브랜치 삭제
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: ${{ inputs.ref_name }}
